name: Build and publish Docker images

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  push_to_registry:
    strategy:
      matrix:
        image:
          - name: "[3.10][poetry-1.1.13]"
            target: "app"
            context: "3.10"
            file: "3.10/poetry.Dockerfile"
            tags: |
              jopplt/python-poetry:3.10
            build-args: |
              POETRY_VERSION=1.1.13
          - name: "[3.10][poetry-1.2.2]"
            target: "app"
            context: "3.10"
            file: "3.10/poetry.Dockerfile"
            tags: |
              jopplt/python:3.10-poetry1.2.2
            build-args: |
              POETRY_VERSION=1.2.2
          - name: "[3.11][poetry-1.2.2]"
            target: "app"
            context: "3.11"
            file: "3.11/poetry.Dockerfile"
            tags: |
              jopplt/python:3.11-poetry1.2.2
            build-args: |
              POETRY_VERSION=1.2.2
      fail-fast: true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "${{ matrix.image.name }}"
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.file }}
          target: ${{ matrix.image.target }}
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ matrix.image.tags }}
          build-args: ${{ matrix.image.build-args }}